# Site settings
title: devanooga
tagline: "A community of tinkerers in and around Chattanooga, TN"
description: "A community of tinkerers in and around Chattanooga, TN"
url: "https://devanooga.com"
github_username:  devanooga
logo: /images/devanooga_logo_red.png
pagination: 5
excerpt_separator: "<!--excerpt-->"

# Build settings
markdown: kramdown
include: ['_pages','_posts']
exclude: ['design_files']

# Default permalink for _posts
permalink: /blog/:year/:month/:day/:title

collections:
  members:
    output: false
    relative_directory: ./_collections/members

twitter:
  username: devanooga

social:
  name: devanooga
  links:
    - https://twitter.com/devanooga
    - https://github.com/devanooga
    - https://www.reddit.com/r/devanooga/

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-seo-tag
